services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    ports:
      - "8081:80"
    depends_on:
      - mysql

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - TZ=${TZ}
      - LOG_ROOT_S100_1=/data/s100-1
      - LOG_ROOT_S100_2=/data/s100-2
      - HIST_DIR_NAME=${HIST_DIR_NAME}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ${LOG_ROOT_S100_1}:/data/s100-1:ro
      - ${LOG_ROOT_S100_2}:/data/s100-2:ro
      - exports:/exports
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  streamlit:
    build:
      context: ./services/streamlit
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - TZ=${TZ}
    ports:
      - "8501:8501"
    depends_on:
      mysql:
        condition: service_healthy
      api:
        condition: service_started

volumes:
  mysql_data:
  exports:
